// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRLDqyU6uKUajVOXsnu-MH-6_g2Qw9q1Q',
    appId: '1:44021174742:web:a762ba6b6bdff5ef531477',
    messagingSenderId: '44021174742',
    projectId: 'todo-advanced-9e94b',
    authDomain: 'todo-advanced-9e94b.firebaseapp.com',
    storageBucket: 'todo-advanced-9e94b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpAUl2-KEV0yXcUyhLVQvFbFiCCJfQSNo',
    appId: '1:44021174742:android:92a4052684f8f92c531477',
    messagingSenderId: '44021174742',
    projectId: 'todo-advanced-9e94b',
    storageBucket: 'todo-advanced-9e94b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUgNZBmp14AJn5zVZ06xBr4h_y8L7HMB0',
    appId: '1:44021174742:ios:8cd20e536fd66ade531477',
    messagingSenderId: '44021174742',
    projectId: 'todo-advanced-9e94b',
    storageBucket: 'todo-advanced-9e94b.appspot.com',
    iosBundleId: 'com.example.todoAdvanced',
  );
}
